from random import *

level = input('Whats the level? ')
Con_treasure = []
Consumable = {'Level 1' : { 1 : 'Light Ammunition',
                              2 : 'Acid Flask',
                              3 : 'Alchemists Fire' ,
                              4 : 'Bottled Lightning' ,
                              5 : 'Liquid Ice' ,
                              6 : 'Tanglefoot Bag' ,
                              7 : 'Thunderstone',
                              8 : 'Bird Feather' ,
                              9 : 'Holy Water' ,
                              10 : 'Ladder feather tolken' ,
                              11 : 'unholy water' ,
                              12 : 'Antidote' ,
                              13 : 'Antiplague' ,
                              14 : 'Cheetahs Elixir' ,
                              15 : 'Darkvision Elixir' ,
                              16 : 'Eagle-eye Elixir' ,
                              17 : 'Minor Elixir of Life' ,
                              18 : 'Runestone' ,
                              19 : 'Nector of purification' ,
                              20 : 'Arsenic' ,
                              21 : 'Giant Centipede Venom' ,
                              22 : 'Minor Healing potion' ,
                              23 : 'Scroll of 1st level spell' ,
                              24 : 'Silversheen' ,
                              25 : 'Smokestick' ,
                              26 : 'Sunrod' ,
                              27 : 'Tindertwig (10)' ,
                              28 : 'Jade Cat' ,
                              29 : 'Owlbear Claw' ,
                              30 : 'Potency Crystal' ,
                              31 : 'Wolf Fang' ,
                              32 : 'Dull Gray Aeon Stone'},
              'Level 2' : { 1 : 'Sleep Arrow' ,
                              2 : 'Holly Bush Feather Token' ,
                              3 : 'Comprehension' ,
                              4 : 'Infiltrators Elixir' ,
                              5 : 'Salamander Elixir' ,
                              6 : 'Stone Fist Elixir' ,
                              7 : 'Winter Wolf Elixir' ,
                              8 : 'Everburning Torch' ,
                              9 : 'Wayfinder' ,
                              10 : 'Oil of Potency' ,
                              11 : 'Oil of Weightlessness' ,
                              12 : 'Belladonna' ,
                              13 : 'Sleep Poison' ,
                              14 : 'Black Adder Venom' ,
                              15 : 'Bloodseeker Beak' ,
                              16 : 'Retruning Clasp' ,
                              17 : 'Wand of 1st Level spell'},
              'Level 3' : { 1 : 'Beacon Shot' ,
                              2 : 'Spellstrike Ammunition 1st' ,
                              3 : 'Vine Arrow' , 
                              4 : 'Chest Feather Token' ,
                              5 : 'Bombers Eye Elixir' ,
                              6 : 'Bravos Brew' ,
                              7 : 'Cats Eye Elixir' ,
                              8 : 'Greater Darkvision Elixir' ,
                              9 : 'Mistform Elixir' ,
                              10 : 'Oil of Mending' ,
                              11 : 'Cytillesh Oil' ,
                              12 : 'Graveroot' ,
                              13 : 'Barkskin Potion' ,
                              14 : 'Invisibillity Potion' ,
                              15 : 'Lesser Healing Potion' ,
                              16 : 'Potion of Water Breathing' ,
                              17 : 'Scroll of 2nd Level Spell' ,
                              18 : 'Feather Step Stone' ,
                              19 : 'Monkey Pin' ,
                              20 : 'Savior Spike'},
              'Level 4' : { 1 : 'Climbing Bolt' ,
                              2 : 'Viper Arrow' ,
                              3 : 'Fan Feather Token' ,
                              4 : 'Lesser Elixir of Life' ,
                              5 : 'Sea Touch Elixir' ,
                              6 : 'Fear  Gem', 
                              7 : 'Wand of 2nd Level Spell'},
              'Level 5' : { 1 : 'Spellstrike Ammunition 2nd' ,
                              2 : 'Dust of Appearance' ,
                              3 : 'Greater Antidote' ,
                              4 : 'Greater Antiplague' ,
                              5 : 'Lesser Bestial Mutagen' ,
                              6 : 'Lesser Bullhead Mutagen' ,
                              7 : 'Lesser Cognitive Mutagen' ,
                              8 : 'Lesser Juggernaut Mutagen' ,
                              9 : 'Lesser Quicksilver Mutagen' ,
                              10 : 'Lesser Silvertongue Mutagen' ,
                              11 : 'Salve of Antiparalysis' ,
                              12 : 'Salve of Slipperiness' ,
                              13 : 'Hunting Spider Venom' ,
                              14 : 'Lesser Potion of Resistance' ,
                              15 : 'Moderate Healing Potion' ,
                              16 : 'Potion of Leaping ' ,
                              17 : 'Scroll of 3rd Level Spell' ,
                              18 : 'Bronze Bull pendant' ,
                              19 : 'Onyx Panther'},
              'Level 6' : { 1 : 'Tree Feather Token' ,
                              2 : 'True Darkvision Elixir' , 
                              3 : 'Greater Oil of Weightlessness' ,
                              4 : 'Giant Scorpion Venom' ,
                              5 : 'Potion of Quickness' , 
                              6 : 'Potion of Swimming' ,
                              7 : 'Grim Trophy' ,
                              8 : 'Mesmerizing Opal' ,
                              9 : 'Mummified Bat' ,
                              10 : 'Wand of 3rd Level Spell'},
              'Level 7' : { 1 : 'Spellstrike Ammunition 3rd' ,
                              2 : 'Anchor Feather Token' ,
                              3 : 'Candle of Revealing' ,
                              4 : 'Giant Wasp Venom' ,
                              5 : 'Malyass Root Paste' ,
                              6 : 'Potion of Disguise' ,
                              7 : 'Young Dragons Breath Potion' ,
                              8 : 'Scroll of 4th Level Spell' ,
                              9 : 'Effervescent Ampule' ,
                              10 : 'Murderers Knot' , 
                              11 : 'Swift Block Cabochon'},
              'Level 8' : { 1 : 'Explosive Ammunition' ,
                              2 : 'Javelin of lighting' ,
                              3 : 'Swan Boat Feather Token' ,
                              4 : 'Elixir of Life' ,
                              5 : 'Candle of Truth' ,
                              6 : 'Baleful Oil' ,
                              7 : 'Blessed Oil' ,
                              8 : 'Nettleweed Residue' ,
                              9 : 'Wyvern Poison' ,
                              10 : 'Greater Healing Potion' ,
                              11 : 'Potion of Flying' , 
                              12 : 'Wand of 4th Level Spell'},
              'Level 9' : { 1 : 'Spellstrike Ammunition 4th' ,
                              2 : 'Dust of Disappearing' ,
                              3 : 'Whip Feather Token' ,
                              4 : 'Bestial Mutagen' ,
                              5 : 'Cognitive Mutagen' ,
                              6 : 'Juggernaut Mutagen' ,
                              7 : 'Quicksilver Mutagen' ,
                              8 : 'Silvertoungue Mutagen' ,
                              9 : 'Lich Dust' ,
                              10 : 'Spider Root' ,
                              11 : 'Potion of Resistance' ,
                              12 : 'Scroll of 5th Level Spell' ,
                              13 : 'Gallows Tooth' ,
                              14 : 'Iron Medallion' ,
                              15 : 'Vanishing Coin'},
             'Level 10' : { 1 : 'Penetrating Ammunition' ,
                              2 : 'Storm Arrow' ,
                              3 : 'Elemental Gem' ,
                              4 : 'True Antidote' ,
                              5 : 'True Antiplague' ,
                              6 : 'Oil of Keen Edges' ,
                              7 : 'Shadow Essence' ,
                              8 : 'Wolfsbane' ,
                              9 : 'Greater Potion of Disguise' ,
                              10 : 'Potion of Toungue' ,
                              11 : 'Emerald Grasshopper'},
             'Level 11' : { 1 : 'Spellstrike Ammunition 5th' ,
                              2 : 'Oil of Animation', 
                              3 : 'Greater Salve of Antiparalysis' ,
                              4 : 'Blightburn Resin' ,
                              5 : 'Scroll of 6th Level Spell' ,
                              6 : 'Mending Lattice'},
             'Level 12' : { 1 : 'Greater Explosive Ammunition' ,
                              2 : 'Greater Elixir of Life' ,
                              3 : 'Slumber Poison' ,
                              4 : 'Adult Dragons Breath Potion' ,
                              5 : 'Major Healing Potion' ,
                              6 : 'Alabaster Reliquary' ,
                              7 : 'Dazinf Tremblant' ,
                              8 : 'Obsidian Reliquary'},
             'Level 13' : { 1 : 'Spellstrike Ammunition 6th' ,
                              2 : 'Greater Bestial Mutagen' ,
                              3 : 'Greater Bullheaded Mutagen' ,
                              4 : 'Greater Cognitive Mutagen' ,
                              5 : 'Greater Juggernaut Mutagen' ,
                              6 : 'Greater Quicksilver Mutagen' ,
                              7 : 'Greater Silvertounge Mutagen' ,
                              8 : 'Deathcap Powder' ,
                              9 : 'Purple Worm Venom' ,
                              10 : 'Greater Potion of Resistance' ,
                              11 : 'Panacea' ,
                              12 : 'Scroll of 7th Level Spell' ,
                              13 : 'Sunstone Beads'},
             'Level 14' : { 1 : 'Ghost Ammunition' ,
                              2 : 'Stone Bullet' ,
                              3 : 'Greater Potion of Flying' ,
                              4 : 'TrueSight Potion' ,
                              5 : 'Vipers Fang'},
             'Level 15' : { 1 : 'Disintergration Bolt' ,
                              2 : 'Spellstrike Ammunition 7th' ,
                              3 : 'Obfuscation Oil' ,
                              4 : 'Dragon Bile' ,
                              5 : 'Insanity Mist' ,
                              6 : 'Scroll of 8th Level Spell' ,
                              7 : 'Ghost Dust'},
             'Level 16' : { 1 : 'True Elixir of Life' ,
                              2 : 'Brimstone Fumes' ,
                              3 : 'Nightmare Vapor'},
             'Level 17' : { 1 : 'Spellstrike Ammunition 8th' ,
                              2 : 'True Bestial Mutagen' ,
                              3 : 'True Bullhead Mutagen' ,
                              4 : 'True Cognitive Mutagen' ,
                              5 : 'True Juggernaut Mutagen' ,
                              6 : 'True Quicksilver Mutagen' ,
                              7 : 'True Silvertounge Mutagen' ,
                              8 : 'Hemlock' ,
                              9 : 'Wyrm Dragons Breath Potion' ,
                              10 :'Scroll of 9th Level Spell' ,
                              11 : 'Spell Sliver'},
             'Level 18' : { 1 : 'Kings Sleep'},
             'Level 19' : { 1 : 'Spellstrike Ammunition 9th' ,
                              2 : 'Black Lotus Extract'},
             'Level 20' : { 1 : 'Elixir of Rejuvination' ,
                              2 : 'Antimagic Oil' ,
                              3 : 'Tears of Death' ,
                              4 : 'Philosophers Stone'}}
consumable_level = { 'Level 1' : { 1 : 10 ,
                                   2 : 4 ,
                                   3 : 2} ,
                     'Level 2' : { 1 : 2 ,
                                   2 : 8 ,
                                   3 : 4} ,
                     'Level 3' : { 2 : 2 ,
                                   3 : 6 ,
                                   4 : 4} ,
                     'Level 4' : { 3 : 2 ,
                                   4 : 4 ,
                                   5 : 4} ,
                     'Level 5' : { 4 : 2 ,
                                   5 : 6 ,
                                   6 : 2} ,
                     'Level 6' : { 5 : 2 ,
                                   6 : 4 ,
                                   7 : 2} ,
                     'Level 7' : { 6 : 2,
                                   7 : 2 ,
                                   8 : 4} ,
                     'Level 8' : { 7 : 2 ,
                                   8 : 4 ,
                                   9 :2} ,
                     'Level 9' : { 8 : 2 ,
                                   9 : 4 ,
                                   10 : 2} ,
                     'Level 10' : { 9 : 2 ,
                                    10 : 4 ,
                                    11 : 2} ,
                     'Level 11' : {10 : 2 ,
                                   11 : 4 ,
                                   12 : 2} ,
                     'Level 12' : { 12 : 6 ,
                                    13 : 2} ,
                     'Level 13' : { 12 : 2 ,
                                    13 : 4 ,
                                    14 : 2} ,
                     'Level 14' : { 13 : 2 ,
                                    14 : 4 ,
                                    15 : 2} ,
                     'Level 15' : { 14  :2 ,
                                    15 : 4 ,
                                    16 : 2} ,
                     'Level 16' : { 16 : 4 ,
                                    17 : 2} ,
                     'Level 17' : { 17 : 4 ,
                                    18 : 2} ,
                     'Level 18' : { 18 : 4 ,
                                    19 : 2} ,
                     'Level 19' : { 19 : 4 ,
                                    20 : 2} ,
                     'Level 20' : {20 : 4}}

number_rolled = consumable_level[f'Level {level}'][int(level)]
table_used = Consumable[f"Level {level}"]
current_level = int(level)
max_level = int(level) + 2
print (level)
if  int(level) == 1:
    print ('You choose 1!')
    while current_level <= max_level :
        number_rolled = consumable_level[f'Level {level}'][int(current_level)]
        current_level += 1
        for x in range(number_rolled) :
            x = randint(1, len(Consumable[f"Level {level}"]))
            Con_treasure.append(Consumable[f"Level {level}"][x]) 
elif level == 12 :
    print ('You choose 12!')
    max_level = level + 2
    while current_level <= max_level :
        current_level = current_level - 1
        number_rolled = consumable_level[f'Level {level}'][int(current_level)]
        current_level += 1
        for x in range(number_rolled) :
            x = randint(1, len(Consumable[f"Level {level}"]))
            Con_treasure.append(Consumable[f"Level {level}"][x]) 
elif level == 20 :
    print ('You choose 20!')
    number_rolled = consumable_level[f'Level {level}'][int(current_level)]
    for x in range(number_rolled) :
        x = randint(1, len(Consumable[f"Level {level}"]))
        Con_treasure.append(Consumable[f"Level {level}"][x]) 
else:
    print ('You choose something other than 1, 12, or 20!')
    while current_level <= max_level :
        current_level = current_level - 1
        number_rolled = consumable_level[f'Level {level}'][int(current_level)]
        current_level += 1
        for x in range(number_rolled) :
            x = randint(1, len(Consumable[f"Level {level}"]))
            Con_treasure.append(Consumable[f"Level {level}"][x])             
print (Con_treasure)   



