from random import *
y = input('How many times do we role?')
for x in range(int(y)) :
  x = randint(1,100)
  print (x)

  Treasure = {'Permanent' : {'2nd Level' : { 1 : 'Expert Light Wooden Sturdy Shield' ,
                                             2 : 'Wand of 1st Level spell' ,
                                             3 : 'Bracers of Armor 1st',
                                             4 : 'Broach of Shielding' ,
                                             5 : 'Expert Handwraps of Mighty Fists' ,
                                             6 : 'Hand of the Mage' , 
                                             7 : 'Hat of disguise'},
                             '3rd Level' : { 1 : '+1 Magic light or medium Armor' ,
                                             2 : 'Cold Iron Warhammer' ,
                                             3 : 'Silver Dagger' ,
                                             4 : '+1 Light or Medium Armor Potency' ,
                                             5 : 'Lesser Mentalists Staff' ,
                                             6 : 'Lesser Staff of Fire' ,
                                             7 : 'Minor Staff of Healing' ,
                                             8 : 'Bracers of Missle Deflection' ,
                                             9 : 'Doubling Rings'},
                             '4th Level' : { 1 : 'Bag of Holding Type 1' ,
                                             2 : '+1 Magic Heavy Armor'
                                             3 : 'Ghost Touch' ,
                                             4 : '+1 Heavy Armor Potency' ,
                                             5 : 'Returning' ,
                                             6 : 'Slick' ,
                                             7 : '+1 Weapon Potency' ,
                                             8 : 'Expert Light Steel Sturdy Shield' ,
                                             9 : 'Wand of 2nd Level Spell' ,
                                             10 : '+1 Magic Weapon' ,
                                             11 : 'Bracers of Armor 2nd' ,
                                             12 : '+1 Handwraps of Mighty Fists' ,
                                             13},
                             '5th Level' : { 1 : 'Ghoul Hide' ,
                                             2 : 'Divine Prayer Beads' ,
                                             3 : 'Skeleton Key' ,
                                             4 : 'Thurible of Revelation' ,
                                             5 : 'Distrupting' ,
                                             6 : 'Glamered' ,
                                             7 : 'Shifting' ,
                                             8 : 'Expert Heavy Wooden Sturdy Shield' ,
                                             9 : 'Lesser Staff of Abjuration' ,
                                             10 : 'Lesser Staff of Conjuration' ,
                                             11 : 'Lesser Staff of Divination' ,
                                             12 : 'Lesser Staff of Enchantment' ,
                                             13 : 'Lesser Staff of Evocation' ,
                                             14 : 'Lesser Staff of Illsuion' ,
                                             15 : 'Lesser Staff of Necromancy' ,
                                             16 : 'Lesser Staff of Transmutation' ,
                                             17 : 'Verdant Staff' ,
                                             18 : 'Dagger of Venom' ,
                                             19 : 'Fighters Fork' ,
                                             20 : 'Clandestine Cloak' ,
                                             21 : 'Coyote Cloak' ,
                                             22 : 'Crafters Eyepiece' ,
                                             23 : 'Hat of the Magi' ,
                                             24 : 'Necklace of Fireballs Type 1' ,
                                             25 : 'Persona Mask' ,
                                             26 : 'Pyhlactery of the Occult' , 
                                             27 : 'Ring of the Ram' ,
                                             28 : 'Tracker Goggles'},
                             '6th Level' : {},
                             '7th Level' : {},
                             '8th Level' : {},
                             '9th Level' : {},
                             '10th level' : {},
                             '11th Level' : {},
                             '12th Level' : {},
                             '13th Level' : {},
                             '14th Level' : {},
                             '15th Level' : {},
                             '16th Level' : {},
                             '17th Level' : {},
                             '18th Level' : {},
                             '19th Level' : {},
                             '20th Level' : {}}
            'Consumable' : {'1st Level' : { 1 : 'Light Ammunition',
                                            2 : 'Acid Flask',
                                            3 : 'Alchemists Fire' ,
                                            4 : 'Bottled Lightning' ,
                                            5 : 'Liquid Ice' 
                                            6 : 'Tanglefoot Bag'
                                            7 : 'Thunderstone',
                                            8 : 'Bird Feather' ,
                                            9 : 'Holy Water' ,
                                            10 : 'Ladder feather tolken' ,
                                            11 : 'unholy water' ,
                                            12 : 'Antidote' ,
                                            13 : 'Antiplague' ,
                                            14 : 'Cheetahs Elixir' ,
                                            15 : 'Darkvision Elixir' ,
                                            16 : 'Eagle-eye Elixir' ,
                                            17 : 'Minor Elixir of Life' ,
                                            18 : 'Runestone' ,
                                            19 : 'Nector of purification' ,
                                            20 : 'Arsenic' ,
                                            21 : 'Giant Centipede Venom' ,
                                            22 : 'Minor Healing potion' ,
                                            23 : 'Scroll of 1st level spell' ,
                                            24 : 'Silversheen' ,
                                            25 : 'Smokestick' ,
                                            26 : 'Sunrod' ,
                                            27 : 'Tindertwig (10)' ,
                                            28 : 'Jade Cat' ,
                                            29 : 'Owlbear Claw' ,
                                            30 : 'Potency Crystal' ,
                                            31 : 'Wolf Fang' ,
                                            32 : 'Dull Gray Aeon Stone'},
                             '2nd Level' : { 1 : 'Sleep Arrow' ,
                                             2 : 'Holly Bush Feather Token' ,
                                             3 : 'Comprehension' ,
                                             4 : 'Infiltrators Elixir' ,
                                             5 : 'Salamander Elixir' ,
                                             6 : 'Stone Fist Elixir' ,
                                             7 : 'Winter Wolf Elixir' ,
                                             8 : 'Everburning Torch' ,
                                             9 : 'Wayfinder' ,
                                             10 : 'Oil of Potency' ,
                                             11 : 'Oil of Weightlessness' ,
                                             12 : 'Belladonna' ,
                                             13 : 'Sleep Poison' ,
                                             14 : 'Black Adder Venom' ,
                                             15 : 'Bloodseeker Beak' ,
                                             16 : 'Retruning Clasp'},
                             '3rd Level' : { 1 : 'Beacon Shot' ,
                                             2 : 'Spellstrike Ammunition 1st' ,
                                             3 : 'Vine Arrow' , 
                                             4 : 'Chest Feather Token' ,
                                             5 : 'Bombers Eye Elixir' ,
                                             6 : 'Bravos Brew' ,
                                             7 : 'Cats Eye Elixir' ,
                                             8 : 'Greater Darkvision Elixir' ,
                                             9 : 'Mistform Elixir' ,
                                             10 : 'Oil of Mending' ,
                                             11 : 'Cytillesh Oil' ,
                                             12 : 'Graveroot' ,
                                             13 : 'Barkskin Potion' ,
                                             14 : 'Invisibillity Potion' ,
                                             15 : 'Lesser Healing Potion' ,
                                             16 : 'Potion of Water Breathing' ,
                                             17 : 'Scroll of 2nd Level Spell' ,
                                             18 : 'Feather Step Stone' ,
                                             19 : 'Monkey Pin' ,
                                             20 : 'Savior Spike'},
                             '4th Level' : { 1 : 'Climbing Bolt' ,
                                             2 : 'Viper Arrow' ,
                                             3 : 'Fan Feather Token' ,
                                             4 : 'Lesser Elixir of Life' ,
                                             5 : 'Sea Touch Elixir' ,
                                             6 : 'Fear  Gem'},
                             '5th Level' : { 1 : 'Spellstrike Ammunition 2nd' ,
                                             2 : 'Dust of Appearance' ,
                                             3 : 'Greater Antidote' ,
                                             4 : 'Greater Antiplague' ,
                                             5 : 'Lesser Bestial Mutagen' ,
                                             6 : 'Lesser Bullhead Mutagen' ,
                                             7 : 'Lesser Cognitive Mutagen' ,
                                             8 : 'Lesser Juggernaut Mutagen' ,
                                             9 : 'Lesser Quicksilver Mutagen' ,
                                             10 : 'Lesser Silvertongue Mutagen' ,
                                             11 : 'Salve of Antiparalysis' ,
                                             12 : 'Salve of Slipperiness' ,
                                             13 : 'Hunting Spider Venom' ,
                                             14 : 'Lesser Potion of Resistance' ,
                                             15 : 'Moderate Healing Potion' ,
                                             16 : 'Potion of Leaping ' ,
                                             17 : 'Scroll of 3rd Level Spell' ,
                                             18 : 'Bronze Bull pendant' ,
                                             19 : 'Onyx Panther'},
                             '6th Level' : {},
                             '7th Level' : {},
                             '8th Level' : {},
                             '9th Level' : {},
                             '10th level' : {},
                             '11th Level' : {},
                             '12th Level' : {},
                             '13th Level' : {},
                             '14th Level' : {},
                             '15th Level' : {},
                             '16th Level' : {},
                             '17th Level' : {},
                             '18th Level' : {},
                             '19th Level' : {},
                             '20th Level' : {}}
               }
