from random import *
y = input('How many times do we role?')
for x in range(int(y)) :
  x = randint(1,100)
  print (x)

  Treasure = {'Permanent' : {'2nd Level' : { 1 : 'Expert Light Wooden Sturdy Shield' ,
                                             2 : 'Wand of 1st Level spell' ,
                                             3 : 'Bracers of Armor 1st',
                                             4 : 'Broach of Shielding' ,
                                             5 : 'Expert Handwraps of Mighty Fists' ,
                                             6 : 'Hand of the Mage' , 
                                             7 : 'Hat of disguise'},
                             '3rd Level' : { 1 : '+1 Magic light or medium Armor' ,
                                             2 : 'Cold Iron Warhammer' ,
                                             3 : 'Silver Dagger' ,
                                             4 : '+1 Light or Medium Armor Potency' ,
                                             5 : 'Lesser Mentalists Staff' ,
                                             6 : 'Lesser Staff of Fire' ,
                                             7 : 'Minor Staff of Healing' ,
                                             8 : 'Bracers of Missle Deflection' ,
                                             9 : 'Doubling Rings'},
                             '4th Level' : { 1 : 'Bag of Holding Type 1' ,
                                             2 : '+1 Magic Heavy Armor'
                                             3 : 'Ghost Touch' ,
                                             4 : '+1 Heavy Armor Potency' ,
                                             5 : 'Returning' ,
                                             6 : 'Slick' ,
                                             7 : '+1 Weapon Potency' ,
                                             8 : 'Expert Light Steel Sturdy Shield' ,
                                             9 : 'Wand of 2nd Level Spell' ,
                                             10 : '+1 Magic Weapon' ,
                                             11 : 'Bracers of Armor 2nd' ,
                                             12 : '+1 Handwraps of Mighty Fists' ,
                                             13},
                             '5th Level' : { 1 : 'Ghoul Hide' ,
                                             2 : 'Divine Prayer Beads' ,
                                             3 : 'Skeleton Key' ,
                                             4 : 'Thurible of Revelation' ,
                                             5 : 'Distrupting' ,
                                             6 : 'Glamered' ,
                                             7 : 'Shifting' ,
                                             8 : 'Expert Heavy Wooden Sturdy Shield' ,
                                             9 : 'Lesser Staff of Abjuration' ,
                                             10 : 'Lesser Staff of Conjuration' ,
                                             11 : 'Lesser Staff of Divination' ,
                                             12 : 'Lesser Staff of Enchantment' ,
                                             13 : 'Lesser Staff of Evocation' ,
                                             14 : 'Lesser Staff of Illsuion' ,
                                             15 : 'Lesser Staff of Necromancy' ,
                                             16 : 'Lesser Staff of Transmutation' ,
                                             17 : 'Verdant Staff' ,
                                             18 : 'Dagger of Venom' ,
                                             19 : 'Fighters Fork' ,
                                             20 : 'Clandestine Cloak' ,
                                             21 : 'Coyote Cloak' ,
                                             22 : 'Crafters Eyepiece' ,
                                             23 : 'Hat of the Magi' ,
                                             24 : 'Necklace of Fireballs Type 1' ,
                                             25 : 'Persona Mask' ,
                                             26 : 'Pyhlactery of the Occult' , 
                                             27 : 'Ring of the Ram' ,
                                             28 : 'Tracker Goggles'},
                             '6th Level' : { 1 : 'Chime of Opening' ,
                                             2 : 'Primeval Mistletoe' ,
                                             3 : 'Traverlers Any-Tool' ,
                                             4 : 'Wounding' ,
                                             5 : 'Lions Shield' ,
                                             6 : 'Spellguard Shield' ,
                                             7 : 'Bloodletting Kukri' ,
                                             8 : 'Boots of Elvenkind' ,
                                             9 : 'Choker of Elocution' ,
                                             10 : 'Dancing Scarf' ,
                                             11 : 'Demon Mask ' ,
                                             12 : 'Eyes of the Eagle' ,
                                             13 : 'Googles of Night' ,
                                             14 : 'Greater Hat of Disguise' ,
                                             15 : 'Lesser Ring of Energy' ,
                                             16 : 'Ring of Lies' ,
                                             17 : 'Slippers of Spider-Climb' ,
                                             18 : 'Tourmaline Spehere Aeon Stone'},
                             '7th Level' : { 1 : '+2 Magic Armor' ,
                                             2 : 'Bag of Holding Type 2' ,
                                             3 : 'Bottled Air' ,
                                             4 : '+2 Armor Potency' ,
                                             5 : 'Expert Heavy Steel Sturdy Shield' ,
                                             6 : 'Mentalists Staff' ,
                                             7 : 'Staff of Fire' ,
                                             8 : 'Lesser Staff of Healing' ,
                                             9 : 'Alchecmist Goggles' ,
                                             10 : 'Boots of Bounding' ,
                                             11 : 'Gloves of Storing' ,
                                             12 : 'Healers Gloves' ,
                                             13 : 'Lesser Ring of Wizardry' ,
                                             14 : 'Master Handwraps of Mighty Fists' ,
                                             15 : 'Necklace of Fireballs Type 2' , 
                                             16 : 'Phylactery of Faithfulness'},
                             '8th Level' : { 1 : '+2 Weapon Potency' ,
                                             2 : 'Invisibility' ,
                                             3 : '+2 Magic Weapon' ,
                                             4 : 'Bracers of Armor 4th' ,
                                             5 : 'Clear Spindle Aeon Stone' ,
                                             6 : '+2 Handwraps of Mighty Fists' ,
                                             7 : 'Lesser Spell Duelists Gloves' ,
                                             8 : 'Lesser Spell Duelists Wand' ,
                                             9 : 'Horeshoes of Speed'},
                             '9th Level' : { 1 : 'Rhino Hide' ,
                                             2 : 'Collar of Inconspicuousness' ,
                                             3 : 'Horn of Blasting' ,
                                             4 : 'Immovable Rod' ,
                                             53 : 'Adamantine Battleaxe' ,
                                             6 : 'Corrosive' ,
                                             7 : 'Energy Resistance' ,
                                             8 : 'Flaming' ,
                                             8 : 'Frost' ,
                                             10 : 'Shock' ,
                                             11 : 'Dragonslayers Shield' ,
                                             12 : 'Forge Warden' ,
                                             13 : 'MasterHeavy Steel Sturdy Shield' ,
                                             14 : 'Staff of Abjuration' ,
                                             15 : 'Staff of Conjuration' ,
                                             16 : 'Staff of Divination' ,
                                             17 : 'Staff of Enchantment' ,
                                             18 : 'Staff of Evocation' ,
                                             19 : 'Staff of Illusion' ,
                                             20 : 'Staff of Necromancy' ,
                                             21 : 'Staff of Transmutation' ,
                                             22 : 'Gloom Blade' ,
                                             23 : 'Armbands of Athleticism' ,
                                             24 : 'Belt of the Five Kings' ,
                                             25 : 'Cloak of the Bat' ,
                                             26 : 'Knapsack of Halflingkind' ,
                                             27 : 'Necklace of Fireballs Type 3' ,
                                             28 : 'Ring of Wizardry'},
                             '10th level' : { 1 : 'Breatplate of Command' ,
                                              2 : 'Celestial Armor' ,
                                              3 : 'Demon Armor' ,
                                              4 : 'Electric Eelskin' ,
                                              5 : 'Maestros Instrument' ,
                                              6 : 'Greater Invisibility' ,
                                              7 : 'Master Light Adamantine Sturdy Shield' ,
                                              8 : 'Flame Toungue' ,
                                              9 : 'Oathbow' ,
                                              10 : 'Cloak of Elvenkind' ,
                                              11 : 'Daredevil Boots' ,
                                              12 : 'Druids Vestments' ,
                                              13 : 'Gold Nodule Aeon Stone' ,
                                              14 : 'Greater Goggles of Night' ,
                                              15 : 'Messengers Ring' ,
                                              16 : 'Ring of Energy Resistance' ,
                                              17 : 'Ring of Counterspells' ,
                                              18 : 'Ring of Maniacal Devices'},
                             '11th Level' : { 1 : '+3 Magic Armor' ,
                                              2 : 'Bag of Holding Type 3' ,
                                              3 : 'Greater Divine Prayer Beads' ,
                                              4 : 'Anarchic' ,
                                              5 : '+3 Armor Potency' ,
                                              6 : 'Axiomatic' ,
                                              7 : 'Holy' ,
                                              8 : 'Unholy' ,
                                              9 : 'Arrow-Catching Shield' ,
                                              10 : 'Greater Verdant Staff' ,
                                              11 : 'Greater Staff of Fire' ,
                                              12 : 'Staff of Healing' ,
                                              13 : 'Greater Verdant Staff' ,
                                              14 : 'Cape of the Mountbank' ,
                                              15 : 'Gorget of the Primal Roar' ,
                                              16 : 'Greater Doubling Rings' ,
                                              17 : 'Necklace of the Fireballs Type 4' ,
                                              18 : 'Robe of the Archmage'},
                             '12th Level' : {},
                             '13th Level' : {},
                             '14th Level' : {},
                             '15th Level' : {},
                             '16th Level' : {},
                             '17th Level' : {},
                             '18th Level' : {},
                             '19th Level' : {},
                             '20th Level' : {}}
            'Consumable' : {'1st Level' : { 1 : 'Light Ammunition',
                                            2 : 'Acid Flask',
                                            3 : 'Alchemists Fire' ,
                                            4 : 'Bottled Lightning' ,
                                            5 : 'Liquid Ice' 
                                            6 : 'Tanglefoot Bag'
                                            7 : 'Thunderstone',
                                            8 : 'Bird Feather' ,
                                            9 : 'Holy Water' ,
                                            10 : 'Ladder feather tolken' ,
                                            11 : 'unholy water' ,
                                            12 : 'Antidote' ,
                                            13 : 'Antiplague' ,
                                            14 : 'Cheetahs Elixir' ,
                                            15 : 'Darkvision Elixir' ,
                                            16 : 'Eagle-eye Elixir' ,
                                            17 : 'Minor Elixir of Life' ,
                                            18 : 'Runestone' ,
                                            19 : 'Nector of purification' ,
                                            20 : 'Arsenic' ,
                                            21 : 'Giant Centipede Venom' ,
                                            22 : 'Minor Healing potion' ,
                                            23 : 'Scroll of 1st level spell' ,
                                            24 : 'Silversheen' ,
                                            25 : 'Smokestick' ,
                                            26 : 'Sunrod' ,
                                            27 : 'Tindertwig (10)' ,
                                            28 : 'Jade Cat' ,
                                            29 : 'Owlbear Claw' ,
                                            30 : 'Potency Crystal' ,
                                            31 : 'Wolf Fang' ,
                                            32 : 'Dull Gray Aeon Stone'},
                             '2nd Level' : { 1 : 'Sleep Arrow' ,
                                             2 : 'Holly Bush Feather Token' ,
                                             3 : 'Comprehension' ,
                                             4 : 'Infiltrators Elixir' ,
                                             5 : 'Salamander Elixir' ,
                                             6 : 'Stone Fist Elixir' ,
                                             7 : 'Winter Wolf Elixir' ,
                                             8 : 'Everburning Torch' ,
                                             9 : 'Wayfinder' ,
                                             10 : 'Oil of Potency' ,
                                             11 : 'Oil of Weightlessness' ,
                                             12 : 'Belladonna' ,
                                             13 : 'Sleep Poison' ,
                                             14 : 'Black Adder Venom' ,
                                             15 : 'Bloodseeker Beak' ,
                                             16 : 'Retruning Clasp'},
                             '3rd Level' : { 1 : 'Beacon Shot' ,
                                             2 : 'Spellstrike Ammunition 1st' ,
                                             3 : 'Vine Arrow' , 
                                             4 : 'Chest Feather Token' ,
                                             5 : 'Bombers Eye Elixir' ,
                                             6 : 'Bravos Brew' ,
                                             7 : 'Cats Eye Elixir' ,
                                             8 : 'Greater Darkvision Elixir' ,
                                             9 : 'Mistform Elixir' ,
                                             10 : 'Oil of Mending' ,
                                             11 : 'Cytillesh Oil' ,
                                             12 : 'Graveroot' ,
                                             13 : 'Barkskin Potion' ,
                                             14 : 'Invisibillity Potion' ,
                                             15 : 'Lesser Healing Potion' ,
                                             16 : 'Potion of Water Breathing' ,
                                             17 : 'Scroll of 2nd Level Spell' ,
                                             18 : 'Feather Step Stone' ,
                                             19 : 'Monkey Pin' ,
                                             20 : 'Savior Spike'},
                             '4th Level' : { 1 : 'Climbing Bolt' ,
                                             2 : 'Viper Arrow' ,
                                             3 : 'Fan Feather Token' ,
                                             4 : 'Lesser Elixir of Life' ,
                                             5 : 'Sea Touch Elixir' ,
                                             6 : 'Fear  Gem'},
                             '5th Level' : { 1 : 'Spellstrike Ammunition 2nd' ,
                                             2 : 'Dust of Appearance' ,
                                             3 : 'Greater Antidote' ,
                                             4 : 'Greater Antiplague' ,
                                             5 : 'Lesser Bestial Mutagen' ,
                                             6 : 'Lesser Bullhead Mutagen' ,
                                             7 : 'Lesser Cognitive Mutagen' ,
                                             8 : 'Lesser Juggernaut Mutagen' ,
                                             9 : 'Lesser Quicksilver Mutagen' ,
                                             10 : 'Lesser Silvertongue Mutagen' ,
                                             11 : 'Salve of Antiparalysis' ,
                                             12 : 'Salve of Slipperiness' ,
                                             13 : 'Hunting Spider Venom' ,
                                             14 : 'Lesser Potion of Resistance' ,
                                             15 : 'Moderate Healing Potion' ,
                                             16 : 'Potion of Leaping ' ,
                                             17 : 'Scroll of 3rd Level Spell' ,
                                             18 : 'Bronze Bull pendant' ,
                                             19 : 'Onyx Panther'},
                             '6th Level' : { 1 : 'Tree Feather Token' ,
                                             2 : 'True Darkvision Elixir' , 
                                             3 : 'Greater Oil of Weightlessness' ,
                                             4 : 'Giant Scorpion Venom' ,
                                             5 : 'Potion of Quickness' , 
                                             6 : 'Potion of Swimming' ,
                                             7 : 'Grim Trophy' ,
                                             8 : 'Mesmerizing Opal' ,
                                             9 : 'Mummified Bat'
                                             10 : 'Wand of 3rd Level Spell'},
                             '7th Level' : { 1 : 'Spellstrike Ammunition 3rd' ,
                                             2 : 'Anchor Feather Token' ,
                                             3 : 'Candle of Revealing' ,
                                             4 : 'Giant Wasp Venom' ,
                                             5 : 'Malyass Root Paste' ,
                                             6 : 'Potion of Disguise' ,
                                             7 : 'Young Dragons Breath Potion' ,
                                             8 : 'Scroll of 4th Level Spell' ,
                                             9 : 'Effervescent Ampule' ,
                                             10 : 'Murderers Knot' , 
                                             11 : 'Swift Block Cabochon'},
                             '8th Level' : { 1 : 'Explosive Ammunition' ,
                                             2 : 'Javelin of lighting' ,
                                             3 : 'Swan Boat Feather Token' ,
                                             4 : 'Elixir of Life' ,
                                             5 : 'Candle of Truth' ,
                                             6 : 'Baleful Oil' ,
                                             7 : 'Blessed Oil' ,
                                             8 : 'Nettleweed Residue' ,
                                             9 : 'Wyvern Poison' ,
                                             10 : 'Greater Healing Potion' ,
                                             11 : 'Potion of Flying' , 
                                             12 : 'Wand of 4th Level Spell' ,
                                             },
                             '9th Level' : { 1 : 'Spellstrike Ammunition 4th' ,
                                             2 : 'Dust of Disappearing' ,
                                             3 : 'Whip Feather Token' ,
                                             4 : 'Bestial Mutagen' ,
                                             5 : 'Cognitive Mutagen' ,
                                             6 : 'Juggernaut Mutagen' ,
                                             7 : 'Quicksilver Mutagen' ,
                                             8 : 'Silvertoungue Mutagen' ,
                                             9 : 'Lich Dust' ,
                                             10 : 'Spider Root' ,
                                             11 : 'Potion of Resistance' ,
                                             12 : 'Scroll of 5th Level Spell' ,
                                             13 : 'Gallows Tooth' ,
                                             14 : 'Iron Medallion' ,
                                             15 : 'Vanishing Coin'},
                             '10th level' : { 1 : 'Penetrating Ammunition' ,
                                              2 : 'Storm Arrow' ,
                                              3 : 'Elemental Gem' ,
                                              4 : 'True Antidote' ,
                                              5 : 'True Antiplague' ,
                                              6 : 'Oil of Keen Edges' ,
                                              7 : 'Shadow Essence' ,
                                              8 : 'Wolfsbane' ,
                                              9 : 'Greater Potion of Disguise' ,
                                              10 : 'Potion of Toungue' ,
                                              11 : 'Emerald Grasshopper'},
                             '11th Level' : { 1 : 'Spellstrike Ammunition 5th' ,
                                              2 : 'Oil of Animation', 
                                              3 : 'Greater Salve of Antiparalysis' ,
                                              4 : 'Blightburn Resin' ,
                                              5 : 'Scroll of 6th Level Spell' ,
                                              6 : 'Mending Lattice'},
                             '12th Level' : {},
                             '13th Level' : {},
                             '14th Level' : {},
                             '15th Level' : {},
                             '16th Level' : {},
                             '17th Level' : {},
                             '18th Level' : {},
                             '19th Level' : {},
                             '20th Level' : {}}
               }
